{
 "title": "M5-HW Dashboard",
 "time": { "from": "2024-02-13T16:29:50.218Z", "to": "2024-05-04T01:29:21.566Z" },
 "panels": [
  {
   "title": "abs_max_features_correlation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select abs_max_features_correlation, timestamp from dummy_metrics"
    }
   ]
  },
  {
   "title": "prediction_drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select prediction_drift, \"timestamp\" from dummy_metrics "
    }
   ]
  },
  {
   "title": "share_missing_values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select share_missing_values, timestamp from dummy_metrics "
    }
   ]
  },
  {
   "title": "fare_amount_median",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "select fare_amount_median, timestamp from dummy_metrics "
    }
   ]
  }
 ]
}